pool:
  vmImage: 'ubuntu-latest' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:

- task: UseDotNet@2
  displayName: 'Install .net core 3.0 (preview)'
  inputs:
    packageType: sdk
    version: '3.1.100'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore Weredev.UI/Weredev.UI.csproj
  displayName: "Restore .Net dependencies"

- script: dotnet build Weredev.UI/Weredev.UI.csproj
  displayName: "Build"

- script: dotnet publish --output $(Build.ArtifactStagingDirectory) Weredev.UI/Weredev.UI.csproj
  displayName: "Publish"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))