pool:
  vmImage: 'ubuntu-latest' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Weredev.UI/Weredev.UI.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Weredev.UI/Weredev.UI.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))