trigger:
- master

pool:
  vmImage: 'windows-latest' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:

- script: dotnet restore
  displayName: "Restore .Net dependencies"

- script: dotnet build Weredev.UI/Weredev.UI.csproj
  displayName: "Build"

- script: dotnet publish --output $(Build.ArtifactStagingDirectory) Weredev.UI/Weredev.UI.csproj
  displayName: "Publish"

- task: PublishBuildArtifacts@1