pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:

- script: dotnet restore
  displayName: "Restore .Net dependencies"

- script: dotnet build
  displayName: "Build"

- script: dotnet publish --output $(Build.ArtifactStagingDirectory)/app/pkg
  displayName: "Publish"

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    ArtifactName: app
    publishLocation: Container