name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: 3.1.101
    - run: DOTNET_CLI_TELEMETRY_OPTOUT=true
    - run: dotnet restore ./Weredev.UI
    - run: dotnet build ./Weredev.UI
    - run: dotnet publish ./Weredev.UI --configuration Release --output ./publish
    - run: cd ./publish && tar -czvf ../weredev.gz.tar *
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: '${{ secrets.HOSTWINDS_USER }}@${{ secrets.HOSTWINDS_SERVER}}'
        privateKey: ${{ secrets.HOSTWINDS_PRIVATE_KEY }}
        command: rm /var/www/weredev.gz.tar -f
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOSTWINDS_SERVER }}
        USERNAME: ${{ secrets.HOSTWINDS_USER }}
        PORT: 22
        KEY: ${{ secrets.HOSTWINDS_PRIVATE_KEY }}
      with:
        source: "./weredev.gz.tar"
        target: "/var/www/"
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTWINDS_SERVER }}
        username: ${{ secrets.HOSTWINDS_USER }}
        key: ${{ secrets.HOSTWINDS_PRIVATE_KEY }}
        port: '22'
        script: |
          rm /var/www/weredev.com.new -rf
          mkdir /var/www/weredev.com.new
          tar -xvf /var/www/weredev.gz.tar -C /var/www/weredev.com.new
          [[ -d /var/www/weredev.com ]] && mv /var/www/weredev.com /var/www/weredev.com.$(date +"%Y%m%d.%H%M%S") 
          mv /var/www/weredev.com.new /var/www/weredev.com
    
