name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: 3.1.101
    - run: dotnet restore ./Weredev.UI
    - run: dotnet build ./Weredev.UI
    - run: dotnet publish ./Weredev.UI --configuration Release --output ./publish
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: '${{ secrets.HOSTWINDS_USER }}@${{ secrets.HOSTWINDS_SERVER}}'
        privateKey: ${{ secrets.HOSTWINDS_PRIVATE_KEY }}
        command: ls -lah
